### PR TITLE
Update README.md

### LINKED ISSUE #13: Invalid or not updated documentation
The sample code on [ Optimization Section](https://github.com/GoogleChrome/custom-tabs-client#optimization) is invalid or not updated. Specifically, `onServiceDisconnected` method is missing and `onCustomTabsServiceConnected` method is duplicated; the real one looks like this:
```java
CustomTabsClient.bindCustomTabsService(this, packageName,
        new CustomTabsServiceConnection() {
            @Override
            public void onCustomTabsServiceConnected(final ComponentName componentName,
                    final CustomTabsClient customTabsClient) {

            }

            @Override
            public void onServiceDisconnected(final ComponentName name) {

            }
        });
```

**UPDATED**

Also, the first parameter of `mayLaunchUrl()` has to be `Uri` object, and yet the sample code passes `String`, which is not correct.

The real signature of `mayLaunchUrl` is below:

```java
public boolean mayLaunchUrl(Uri url, Bundle extras, List<Bundle> otherLikelyBundles)
```

### PR DESCRIPTION
**Pull request by shaunkawano**
Closes #13

### CODE REVIEW

**Comment by shaunkawano** [comment]
I signed it!

**Comment by pasko** [comment]
Thank you for the report! (next time please look at the readme how to file issues on crbug.com)

We haven't established the process with external pull requests, so abandoning this one, but I fixed the issue you pointed at here: https://github.com/GoogleChrome/custom-tabs-client/commit/01ce70f5cda6b288cc80d34e401de7400bcd42c9

Sorry for inconvenience.

**Comment by pasko** [comment]
... and I was stupid, here is a better change: https://codereview.chromium.org/1365853004/

**Comment by shaunkawano** [comment]
Thank you for your response and make things right! 

And, sorry for not reading both README AND CONTRIBUTING documentation.. I will make sure I read how-to-contribute documentations carefully next time.

**Pull request closed without merging**
