### PR TITLE
master

### PR DESCRIPTION
**Pull request by IgorGanapolsky**

### CODE REVIEW

**Comment by pasko** [comment]
Hey, if you want to make a contribution to this repository, please follow these instructions:
https://github.com/GoogleChrome/custom-tabs-client/blob/master/CONTRIBUTING.md

Sorry for inconvenience.

Setting code aside, can you educate us on what the specific benefits are for updating gradle versions. Are old versions blocking something at the moment?

**Comment by IgorGanapolsky** [comment]
The benefits is that developers can easily work with your repo using Instant Run in Android Studio.

**Comment by andreban** [comment]
Hi @IgorGanapolsky , Thanks for the Pull Request. The Instant Run feature is still on Android Studio Canary and it seems we would have to include and alpha version of the build tools ('com.android.tools.build:gradle:2.0.0-alpha6') for it work. It's probably worth waiting until the feature reaches mainstream.

**Comment by IgorGanapolsky** [comment]
@pasko What in the world is Rietveld?  I tried to learn about it, but it seems old-school :)

**Comment by pasko** [comment]
It is truly very old school, but it is *the* tool in use for collaborative development of the Chrome browser. Sorry about that :)

**Pull request closed without merging**
