### PR TITLE
Fix JavaDoc

### PR DESCRIPTION
**Pull request by massongit**
I fixed "calback" to "callback" in JavaDoc.

### CODE REVIEW

**Comment by massongit** [comment]
I signed it!

**Comment by sheepmaster** [comment]
Hi! Sorry if you haven't gotten a response (from a human) on this pull request so far, but contributing to this project works via Gerrit – see https://chromium.googlesource.com/custom-tabs-client/+/master/CONTRIBUTING.md. Thanks!

**Comment by massongit** [comment]
@sheepmaster Thank you for your information!

**Comment by massongit** [comment]
I moved this issue to https://chromium-review.googlesource.com/c/custom-tabs-client/+/935602.

**Pull request closed without merging**
